// Generated by Wrangler by running `wrangler types`

interface Env {
	R2_ACCESS_KEY: "15d9ce55a48b6dce7c1ccc9251908144";
	PASSWORD: string;
	R2_SECRET: string;
	IMAGE_BUCKET: R2Bucket;
	DB: D1Database;
}
